import Link from "next/link";

export const metadata = {
    title: 'My store section',
    description: 'Generated by Next.js',
  }
  

export default function StoreLayout({ children }) {
    return (
        <>
            <nav>
                <h3>Store Section</h3>
                <ul>
                    <Link href="/store/categories"><li>Categories</li></Link>
                    
                    <Link href="/store/categories/laptop"><li>Products</li></Link>
                </ul>
            </nav>
            {children}
        </>
    )
}